### ISSUE TITLE
[FEATURE] Display critique.gatech.edu grade distribution data for O01/ OAN/ OCY sections of each course.

### ISSUE THREAD

**Issue by willisjs** [omshub/website#97] opened 2022-06-05 10:38 UTC

**Comment by MatthewCaseres** [comment] 2022-06-12 03:13
What does it look like to solve this problem? What is the next step we need to take. Can you take it?

**Comment by driscoll42** [comment] 2022-06-12 13:20
Duplicate of #4 and #5

**Closed by driscoll42** 2022-06-12 13:20 UTC
Labels: enhancement
